# Generated by Django 4.0.1 on 2022-02-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('iLevel', models.IntegerField()),
                ('guildRole', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildName', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=64)),
                ('charName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guildboard.character')),
                ('content', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guildboard.content')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guildboard.classe'),
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guildboard.guild'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
