# Generated by Django 4.0.1 on 2022-02-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='content',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guildboard.content'),
        ),
    ]
