# Generated by Django 4.0.1 on 2022-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='className',
        ),
        migrations.AddField(
            model_name='character',
            name='classe',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='guildRole',
            field=models.CharField(default='Member', max_length=64),
        ),
    ]
