# Generated by Django 4.0.1 on 2022-02-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0002_groups_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guilds',
            name='charName',
        ),
        migrations.AddField(
            model_name='characters',
            name='guild',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guildboard.guilds'),
        ),
    ]
