# Generated by Django 4.0.1 on 2022-02-02 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0003_remove_guilds_charname_characters_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('iLevel', models.IntegerField()),
                ('guildRole', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='CharClass',
            new_name='Classe',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Guilds',
            new_name='Guild',
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
        migrations.AddField(
            model_name='character',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guildboard.classe'),
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guildboard.guild'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='charName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guildboard.character'),
        ),
    ]
