# Generated by Django 4.0.1 on 2022-02-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0005_alter_character_ilevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='iLevel',
            field=models.IntegerField(),
        ),
    ]
