# Generated by Django 4.0.1 on 2022-02-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guildboard', '0006_alter_character_ilevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guildboard.guild'),
        ),
    ]
